name: deep-water
channels:
  - conda-forge
  - anaconda
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pip
  - pylint
  - python=3.8.5
  - pip:
      - Pillow
      - rasterio
      - requests
      - tensorflow==2.3
